### ISSUE TITLE
When downsample I got an odd number

### ISSUE THREAD

**Issue by Wendell-Zhang-GitHub** [aasensio/learned_mfbd#1]
img_size=( 216 x 300 )
Downsample I'll get ( 108 x 150 ) → (54 x 75) → (27 x 37)
Then,When upsample  ( 27 x 2 = 54 , 37 x 2 = 74) and    74 != 75
What shuold I do please !
Thank you for disturbing !

**Comment by aasensio** [comment]
The architecture of the network requires the input image to have dimensions that are divisible by 2^3 if you want to have the output and the input of the same dimensions. As you say, 216/2^3=27, which is integer. On the other hand, 300/2^3=37.5, which is not integer. This can be solved by cropping the image to the nearest size that is divisible by 2^3, for example 216 x 296 or 216 x 304.
